name: dds-examples
channels:
  - conda-forge
  - fondazione-cmcc
dependencies:
  - python
  - pip
  - datetime
  - os
  - pathlib
  - subprocess
  - warnings
  - cartopy
  - graphviz
  - hvplot
  - IPython
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - xarray
  - ddsapi
  - appmode
